name = "dmt-mashups"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { DISCORD_WEBHOOK_URL = "" }

[env.production]
vars = { DISCORD_WEBHOOK_URL = "" }

[unsafe.metadata.observability]
enabled = true

[observability]
enabled = true

[triggers]
crons = ["0 17 * * SUN", "0 17 * * THU"]